// Generated by CoffeeScript 1.4.0
(function() {
  var GithubArt, fs, program,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  fs = require('fs');

  program = require('commander');

  GithubArt = require('./GithubArt').GithubArt;

  module.exports.Program = (function() {

    function Program(options) {
      this.options = options != null ? options : {};
      this.run = __bind(this.run, this);

      return this;
    }

    Program.prototype.run = function() {
      return console.log("Hello world");
    };

    Program.create = function(options) {
      if (options == null) {
        options = {};
      }
      return new Program(options);
    };

    Program.run = function() {
      return (Program.create()).run();
    };

    return Program;

  })();

}).call(this);
