// Generated by CoffeeScript 1.4.0
(function() {
  var exec, spawn, _ref;

  _ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

  module.exports.call = function(command, args, fn) {
    var arg, cmdline, _i, _len;
    if (args == null) {
      args = [];
    }
    if (fn == null) {
      fn = null;
    }
    cmdline = [];
    cmdline.push("\"" + command + "\"");
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      arg = args[_i];
      cmdline.push("\"" + arg + "\"");
    }
    console.log(cmdline.join(' '));
    return exec(cmdline.join(' '), function(err, stdout, stderr) {
      if (err != null) {
        console.error("Error :");
        return console.dir(err);
      }
      if (fn) {
        return fn(err, stdout, stderr);
      }
    });
  };

  module.exports.system = function(command, args) {
    return spawn(command, args, {
      stdio: "inherit"
    });
  };

}).call(this);
